const DEFAULT_LIMIT = 50;
const MAX_LIMIT = 100;

const CACHE_TTL_SECONDS = 3600;

export default {
  async fetch(request, env, ctx) {
    try {
      if (request.method === "OPTIONS") {
        return new Response(null, {
          status: 204,
          headers: corsHeaders()
        });
      }

      const url = new URL(request.url);

      if (url.pathname === "/" || url.pathname === "/health") {
        return jsonResponse({
          success: true,
          service: "Ticketmaster Parking Event Finder",
          source: "Ticketmaster Discovery Feed",
          architecture: {
            completeIndex: "events.json",
            parkingIndex: "parking.json",
            runtimeSearch: "prebuilt search shards"
          },
          endpoints: ["/events", "/parking", "/stats"]
        });
      }

      if (url.pathname === "/events") {
        return handleSearch(url, env, ctx, "events");
      }

      if (url.pathname === "/parking") {
        return handleSearch(url, env, ctx, "parking");
      }

      if (url.pathname === "/stats") {
        return handleStats(env, ctx);
      }

      return jsonResponse(
        {
          success: false,
          error: "Not found"
        },
        404
      );
    } catch (error) {
      console.error(error);

      return jsonResponse(
        {
          success: false,
          error: error?.message || "Unexpected server error"
        },
        500
      );
    }
  }
};

async function handleSearch(url, env, ctx, type) {
  const keyword = (url.searchParams.get("keyword") || "").trim();
  const city = (url.searchParams.get("city") || "").trim();
  const state = (url.searchParams.get("stateCode") || "").trim();
  const startDate = (url.searchParams.get("startDate") || "").trim();
  const endDate = (url.searchParams.get("endDate") || "").trim();

  const requestedLimit =
    Number(url.searchParams.get("limit")) || DEFAULT_LIMIT;

  const limit = Math.min(
    Math.max(requestedLimit, 1),
    MAX_LIMIT
  );

  const offset = Math.max(
    Number(url.searchParams.get("offset")) || 0,
    0
  );

  validateDate(startDate, "startDate");
  validateDate(endDate, "endDate");

  if (startDate && endDate && startDate > endDate) {
    throw new Error("startDate cannot be after endDate");
  }

  if (
    !keyword &&
    !city &&
    !state &&
    !startDate &&
    !endDate
  ) {
    return jsonResponse(
      {
        success: false,
        error:
          "A search filter is required. Use keyword, city, stateCode, startDate, or endDate."
      },
      400
    );
  }

  const candidates = await loadCandidates({
    type,
    keyword,
    city,
    state,
    startDate,
    endDate,
    env,
    ctx
  });

  const filtered = candidates.filter((event) =>
    matchesFilters(event, {
      keyword,
      city,
      state,
      startDate,
      endDate
    })
  );

  const results = filtered.slice(
    offset,
    offset + limit
  );

  return jsonResponse({
    success: true,
    query: {
      type,
      keyword: keyword || null,
      city: city || null,
      stateCode: state || null,
      startDate: startDate || null,
      endDate: endDate || null,
      offset,
      limit
    },
    summary: {
      candidateEvents: candidates.length,
      matchingEvents: filtered.length,
      returned: results.length
    },
    results,
    parkingCheck:
      type === "events"
        ? {
            enabled: true,
            meaning:
              "Each event contains parkingMatches generated by the GitHub feed processor.",
            eventsWithParkingMatches: filtered.filter(
              (event) =>
                Array.isArray(event.parkingMatches) &&
                event.parkingMatches.length > 0
            ).length
          }
        : {
            enabled: true,
            meaning:
              "Each parking event contains matchedEventIds generated by the GitHub feed processor."
          }
  });
}

async function loadCandidates({
  type,
  keyword,
  city,
  state,
  startDate,
  endDate,
  env,
  ctx
}) {
  const baseUrl =
    type === "events"
      ? env.EVENT_SEARCH_BASE_URL
      : env.PARKING_SEARCH_BASE_URL;

  if (!baseUrl) {
    throw new Error(
      `${type === "events" ? "EVENT_SEARCH_BASE_URL" : "PARKING_SEARCH_BASE_URL"} is not configured`
    );
  }

  const urls = buildShardUrls({
    baseUrl,
    type,
    keyword,
    city,
    state,
    startDate,
    endDate
  });

  if (!urls.length) {
    throw new Error("Unable to select a search index shard");
  }

  const responses = await Promise.all(
    urls.map((shardUrl) =>
      fetchCachedJson(shardUrl, env, ctx)
    )
  );

  const merged = new Map();

  for (const payload of responses) {
    for (const event of payload?.events || []) {
      if (!event?.id) continue;
      merged.set(event.id, event);
    }
  }

  return [...merged.values()];
}

function buildShardUrls({
  baseUrl,
  type,
  keyword,
  city,
  state,
  startDate,
  endDate
}) {
  const urls = [];
  const seen = new Set();

  const add = (path) => {
    const url = `${baseUrl.replace(/\/+$/, "")}/${path}`;
    if (!seen.has(url)) {
      seen.add(url);
      urls.push(url);
    }
  };

  if (keyword) {
    const firstToken =
      normalizeText(keyword).split(" ").find(Boolean);

    if (firstToken) {
      const shard = shardKey(firstToken);

      add(`${type}/attraction/${shard}.json`);
      add(`${type}/name/${shard}.json`);
    }
  } else if (city) {
    add(`${type}/city/${shardKey(city)}.json`);
  } else if (state) {
    add(`${type}/state/${normalizeText(state)}.json`);
  }

  const months = monthRange(
    startDate || null,
    endDate || null
  );

  if (months.length) {
    for (const month of months) {
      add(`${type}/month/${month}.json`);
    }
  }

  /*
   * If a keyword/city/state is present, the corresponding shard is the
   * primary candidate set and date is an additional filter.
   *
   * If only a date range is supplied, month shards are the candidate set.
   */
  return urls;
}

function monthRange(startDate, endDate) {
  if (!startDate && !endDate) return [];

  const start = startDate
    ? new Date(`${startDate}T00:00:00Z`)
    : new Date();

  const end = endDate
    ? new Date(`${endDate}T00:00:00Z`)
    : new Date(start);

  if (!startDate) {
    start.setUTCDate(1);
  }

  if (!endDate) {
    end.setUTCMonth(end.getUTCMonth() + 1);
    end.setUTCDate(0);
  }

  start.setUTCDate(1);
  end.setUTCDate(1);

  const result = [];
  const cursor = new Date(start);

  while (cursor <= end && result.length < 24) {
    const year = cursor.getUTCFullYear();
    const month = String(
      cursor.getUTCMonth() + 1
    ).padStart(2, "0");

    result.push(`${year}-${month}`);
    cursor.setUTCMonth(
      cursor.getUTCMonth() + 1
    );
  }

  return result;
}

function matchesFilters(
  event,
  {
    keyword,
    city,
    state,
    startDate,
    endDate
  }
) {
  if (keyword && !matchesKeyword(event, keyword)) {
    return false;
  }

  if (
    city &&
    normalizeText(event.venue?.city) !==
      normalizeText(city)
  ) {
    return false;
  }

  if (
    state &&
    normalizeText(event.venue?.state) !==
      normalizeText(state)
  ) {
    return false;
  }

  if (
    startDate &&
    event.localDate &&
    event.localDate < startDate
  ) {
    return false;
  }

  if (
    endDate &&
    event.localDate &&
    event.localDate > endDate
  ) {
    return false;
  }

  return true;
}

function matchesKeyword(event, keyword) {
  const queryTokens = normalizeText(keyword)
    .split(" ")
    .filter(Boolean);

  if (!queryTokens.length) return true;

  const haystack = normalizeText(
    [
      event.name,
      event.searchText,
      event.venue?.name,
      event.venue?.city,
      event.venue?.state,
      ...(event.attractions || []).map(
        (item) => item?.name
      )
    ].join(" ")
  );

  return queryTokens.every((token) =>
    haystack.includes(token)
  );
}

async function fetchCachedJson(
  url,
  env,
  ctx
) {
  const cache = caches.default;
  const request = new Request(url, {
    method: "GET"
  });

  let response = await cache.match(request);

  if (!response) {
    response = await fetch(url, {
      headers: {
        Accept: "application/json"
      },
      cf: {
        cacheTtl: CACHE_TTL_SECONDS,
        cacheEverything: true
      }
    });

    if (!response.ok) {
      throw new Error(
        `Search shard request failed (${response.status}): ${url}`
      );
    }

    ctx.waitUntil(
      cache.put(
        request,
        response.clone()
      )
    );
  }

  return response.json();
}

async function handleStats(env, ctx) {
  const base =
    env.EVENT_SEARCH_BASE_URL;

  if (!base) {
    throw new Error(
      "EVENT_SEARCH_BASE_URL is not configured"
    );
  }

  const manifestUrl =
    `${base.replace(/\/+$/, "")}/manifest.json`;

  const manifest =
    await fetchCachedJson(
      manifestUrl,
      env,
      ctx
    );

  return jsonResponse({
    success: true,
    ...manifest
  });
}

function validateDate(value, field) {
  if (!value) return;

  if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    throw new Error(
      `${field} must use YYYY-MM-DD`
    );
  }
}

function shardKey(value) {
  const normalized = normalizeText(value)
    .replace(/[^a-z0-9]/g, "");

  if (!normalized) return "zz";

  return normalized
    .slice(0, 2)
    .padEnd(2, "0");
}

function normalizeText(value) {
  return String(value || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
    "Cache-Control": "no-store"
  };
}

function jsonResponse(
  data,
  status = 200
) {
  return new Response(
    JSON.stringify(data, null, 2),
    {
      status,
      headers: {
        "Content-Type":
          "application/json; charset=utf-8",
        ...corsHeaders()
      }
    }
  );
}
